# Generated by Django 4.1.3 on 2022-11-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_todo_description_alter_todo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
