# Generated by Django 4.1.3 on 2022-11-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_todo_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Status',
            field=models.CharField(choices=[('1', 'OPEN'), ('2', 'WORKING'), ('3', 'OVERDUE'), ('4', 'COMPLETED')], default='1', max_length=10),
        ),
    ]
