# Generated by Django 4.1.3 on 2022-11-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
