# Generated by Django 4.1.3 on 2022-11-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_alter_todo_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Due',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
